; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
build_cache_dir = .pio/buildcache

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Board-spezifische Builds für 16MB Flash
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv

board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram = 0
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.embed_files = data/timezone16.bin
board_build.cppstd = c++17

lib_deps =
    adafruit/Adafruit NeoPixel@^1.11.0
    rzeldent/micro-timezonedb@^1.0.4

build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DFIRMWARE_VERSION=\"1.0.0\"

; Upload-Geschwindigkeit
upload_speed = 921600

; Standard-Dateisystem für alle Umgebungen
board_build.filesystem = littlefs

[env:esp32s3_Serial]
upload_port = COM24

[env:esp32s3_OTA]
upload_protocol = espota
upload_port = 172.24.115.132


[env:esp32s3_CAN]

upload_protocol = custom
upload_command = python canable_upload.py --node-id 13 --bitrate 250000 --timeout 30 .pio/build/${PIOENV}/firmware.bin